<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Faiz Habibullah">
<meta name="dcterms.date" content="2025-01-14">

<title>PENGARUH EKSPOR LADA HITAM TERHADAP PEREKONOMIAN INDONESIA 2012-2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PENGARUH EKSPOR LADA HITAM TERHADAP PEREKONOMIAN INDONESIA 2012-2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Faiz Habibullah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>logo APP</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">0.1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="0.1.1">
<h3 data-number="0.1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">0.1.1</span> Latar belakang</h3>
<p>Indonesia dikenal sebagai salah satu penghasil lada hitam terbesar di dunia. Sebagai negara tropis dengan kondisi tanah yang subur dan iklim yang mendukung, Indonesia telah lama menjadi pusat produksi lada hitam yang penting, baik untuk pasar domestik maupun internasional. Pada tahun-tahun terakhir, lada hitam Indonesia menjadi komoditas ekspor yang sangat berharga, dengan negara-negara tujuan utama seperti Amerika Serikat, India, dan Eropa. Perekonomian Indonesia, yang sangat bergantung pada sektor pertanian, terus berusaha untuk mengoptimalkan potensi ekspor komoditas agrikultur, termasuk lada hitam. Ekspor lada hitam memiliki dampak langsung terhadap perekonomian, mulai dari penciptaan lapangan kerja di sektor pertanian hingga kontribusinya dalam meningkatkan pendapatan negara. Namun, dalam periode antara 2012 hingga 2024, ada dinamika yang cukup signifikan dalam perdagangan global lada hitam, termasuk fluktuasi harga pasar internasional, kebijakan perdagangan global, dan faktor-faktor eksternal seperti perubahan iklim yang dapat mempengaruhi hasil produksi. Selain itu, sektor pertanian, khususnya komoditas ekspor seperti lada hitam, berhadapan dengan berbagai tantangan, termasuk persaingan dari negara penghasil lada lain, serta kebijakan proteksionisme yang dapat membatasi akses pasar internasional. Di sisi lain, peluang untuk meningkatkan ekspor lada hitam juga terbuka lebar, seiring dengan permintaan yang terus berkembang di pasar global yang mencari bahan pangan dan rempah-rempah alami berkualitas tinggi. Oleh karena itu, penelitian mengenai pengaruh ekspor lada hitam terhadap perekonomian Indonesia antara tahun 2012 hingga 2024 menjadi penting untuk memahami bagaimana perdagangan komoditas ini memberikan dampak positif dan tantangan yang perlu diatasi dalam rangka meningkatkan kesejahteraan petani serta kontribusinya terhadap perekonomian nasional. Analisis ini diharapkan dapat memberikan gambaran yang jelas mengenai potensi sektor ekspor lada hitam dalam mendukung stabilitas ekonomi Indonesia, serta mengidentifikasi kebijakan yang tepat untuk memperkuat posisi Indonesia di pasar global. Latar belakang ini memberikan gambaran tentang pentingnya lada hitam bagi perekonomian Indonesia, serta beberapa faktor yang mempengaruhi ekspor lada hitam dari tahun 2012 hingga 2024. Anda dapat memperluasnya dengan data dan analisis lebih lanjut untuk mendalami pengaruh ekspor lada hitam secara lebih detail</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="0.1.2">
<h3 data-number="0.1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">0.1.2</span> Ruang lingkup</h3>
<p>Penelitian ini akan membahas pengaruh ekspor lada hitam terhadap perekonomian Indonesia pada periode 2012 hingga 2024, dengan fokus pada aspek-aspek yang berkaitan dengan perkembangan perdagangan lada hitam, faktor-faktor yang mempengaruhinya, serta dampak ekonomi yang ditimbulkan. Adapun ruang lingkup penelitian ini meliputi beberapa area sebagai berikut: 1. Aspek Perdagangan Lada Hitam: o Analisis tren ekspor lada hitam Indonesia dari tahun 2012 hingga 2024, termasuk volume dan nilai ekspor. o Identifikasi negara tujuan utama ekspor lada hitam Indonesia selama periode tersebut. o Perbandingan ekspor lada hitam Indonesia dengan negara produsen lain. 2. Faktor-Faktor yang Mempengaruhi Ekspor Lada Hitam: o Faktor produksi lada hitam di Indonesia, termasuk produktivitas dan kualitas hasil. o Pengaruh kebijakan perdagangan dalam negeri dan internasional terhadap ekspor lada hitam. o Dampak perubahan iklim dan cuaca terhadap hasil panen lada hitam. o Tren permintaan global dan preferensi konsumen terhadap lada hitam. 3. Dampak Ekspor Lada Hitam terhadap Perekonomian Indonesia: o Kontribusi ekspor lada hitam terhadap Pendapatan Domestik Bruto (PDB) sektor pertanian. o Dampak ekspor lada hitam terhadap pendapatan petani dan kesejahteraan masyarakat di daerah penghasil lada. o Pengaruh ekspor lada hitam terhadap neraca perdagangan Indonesia dan perekonomian nasional secara keseluruhan. 4. Tantangan dan Peluang Ekspor Lada Hitam: o Identifikasi tantangan utama dalam meningkatkan volume ekspor lada hitam Indonesia, seperti masalah kualitas, persaingan global, dan hambatan perdagangan. o Peluang pasar ekspor lada hitam Indonesia, baik di pasar internasional yang sudah ada maupun potensi pasar baru. 5. Perkembangan Kebijakan Pemerintah: o Tinjauan kebijakan pemerintah Indonesia terkait dengan ekspor lada hitam, termasuk upaya untuk meningkatkan daya saing produk Indonesia di pasar global. o Dampak kebijakan pemerintah terhadap sektor pertanian dan ekspor lada hitam di Indonesia. Penelitian ini akan membatasi pembahasan pada periode antara tahun 2012 hingga 2024, dengan fokus pada data dan informasi yang relevan untuk periode tersebut. Analisis akan dilakukan berdasarkan data yang tersedia mengenai ekspor lada hitam, kebijakan yang berlaku, serta faktor-faktor yang mempengaruhi perdagangan lada hitam dalam konteks ekonomi Indonesia. Ruang lingkup ini memberikan batasan yang jelas mengenai apa yang akan dibahas dalam penelitian, sehingga fokus pembahasan tetap terjaga dan sesuai dengan topik yang diteliti.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="0.1.3">
<h3 data-number="0.1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">0.1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Bagaimana pengaruh ekspor lada hitam terhadap perekonomian Indonesia pada periode tersebut?</li>
<li>Apa tantangan dan peluang yang dihadapi Indonesia dalam meningkatkan ekspor lada hitam pada periode 2012-2024?</li>
<li>Bagaimana tren ekspor lada hitam Indonesia pada periode 2012-2024?</li>
<li>Apa saja faktor yang mempengaruhi ekspor lada hitam Indonesia selama periode 2012-2024?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="0.1.4">
<h3 data-number="0.1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">0.1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Penelitian ini bertujuan untuk mengkaji secara mendalam pengaruh ekspor lada hitam terhadap perekonomian Indonesia pada periode 2012 hingga 2024. Adapun tujuan khusus dari penelitian ini adalah sebagai berikut: 1. Menganalisis tren ekspor lada hitam Indonesia selama periode 2012 hingga 2024, mencakup volume ekspor, nilai ekspor, serta negara-negara tujuan utama ekspor lada hitam Indonesia. 2. Mengidentifikasi faktor-faktor yang mempengaruhi ekspor lada hitam Indonesia, baik yang bersifat internal (seperti produktivitas, kualitas, dan kebijakan pertanian) maupun eksternal (seperti permintaan pasar global, perubahan iklim, dan kebijakan perdagangan internasional). 3. Menilai dampak ekspor lada hitam terhadap perekonomian Indonesia, terutama dari segi kontribusinya terhadap Produk Domestik Bruto (PDB) sektor pertanian, pendapatan petani, serta neraca perdagangan Indonesia. 4. Mengidentifikasi tantangan yang dihadapi Indonesia dalam meningkatkan ekspor lada hitam, serta peluang yang dapat dimanfaatkan untuk memperbesar pangsa pasar global lada hitam Indonesia. 5. Mengevaluasi kebijakan pemerintah terkait dengan ekspor lada hitam dan pengaruhnya terhadap sektor pertanian dan ekonomi nasional, serta memberikan rekomendasi kebijakan untuk mendukung ekspor lada hitam yang berkelanjutan. Penelitian ini diharapkan dapat memberikan gambaran yang komprehensif tentang peran ekspor lada hitam dalam perekonomian Indonesia, serta memberikan wawasan mengenai upaya-upaya yang perlu dilakukan untuk mengoptimalkan potensi ekspor lada hitam di masa depan. Tujuan penelitian ini memberikan arah yang jelas mengenai apa yang ingin dicapai dalam studi ini, serta bagaimana penelitian akan menganalisis dan memberikan kontribusi terhadap pemahaman tentang pengaruh ekspor lada hitam terhadap perekonomian Indonesia. Penelitian ini diharapkan dapat memberikan manfaat baik secara teoretis maupun praktis, baik bagi pengambil kebijakan, pelaku industri, maupun masyarakat umum. Adapun manfaat yang diharapkan dari penelitian ini menambah wawasan dan literatur terkait dengan peran ekspor lada hitam dalam perekonomian Indonesia, khususnya dalam sektor pertanian dan perdagangan internasional.Memberikan kontribusi terhadap pengembangan teori dan penelitian di bidang ekonomi, perdagangan internasional, dan pertanian, dengan fokus pada komoditas ekspor dari negara berkembang seperti Indonesia.</p>
</section>
<section id="package" class="level3" data-number="0.1.5">
<h3 data-number="0.1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">0.1.5</span> Package</h3>
<p>Ini tidak wajib ada di tulisan anda tapi anda dapat menunjukkan Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#/warning: false</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#/echo: true</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="0.2">
<h2 data-number="0.2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">0.2</span> Studi pustaka</h2>
<p>Ekspor komoditas agrikultur, termasuk lada hitam, memainkan peran penting dalam perekonomian Indonesia. Menurut penelitian yang dilakukan oleh Yusuf dan Daryanto (2019), ekspor produk pertanian berkontribusi terhadap pendapatan negara dan penciptaan lapangan kerja di sektor pertanian. Lada hitam, sebagai salah satu komoditas ekspor utama, memiliki pengaruh signifikan terhadap stabilitas neraca perdagangan Indonesia. Penelitian oleh Anggraini (2021) menyebutkan bahwa peningkatan volume ekspor lada hitam dapat mengurangi defisit neraca perdagangan Indonesia, dengan meningkatkan aliran devisa yang digunakan untuk membiayai sektor-sektor lain yang membutuhkan impor bahan baku.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="0.3">
<h2 data-number="0.3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">0.3</span> Metode penelitian</h2>
</section>
<section id="tabel-data-tahun" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Tabel Data Tahun</h1>
<p>Berikut adalah data yang disajikan dalam bentuk tabel:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>x (Nilai 1)</th>
<th>y (Nilai 2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>48037.1</td>
<td>298125.5</td>
</tr>
<tr class="even">
<td>2013</td>
<td>29273</td>
<td>186046.7</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>16802.2</td>
<td>136465.3</td>
</tr>
<tr class="even">
<td>2015</td>
<td>33437.1</td>
<td>302020.5</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>28598.1</td>
<td>220679.4</td>
</tr>
<tr class="even">
<td>2017</td>
<td>15827.5</td>
<td>87184.4</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>14129.3</td>
<td>41716.3</td>
</tr>
<tr class="even">
<td>2019</td>
<td>17415.1</td>
<td>43125.4</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>27921.9</td>
<td>65641.6</td>
</tr>
<tr class="even">
<td>2021</td>
<td>14195.2</td>
<td>47893.5</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>13182.2</td>
<td>50427.9</td>
</tr>
<tr class="even">
<td>2023</td>
<td>9276.9</td>
<td>36104.4</td>
</tr>
</tbody>
</table>
<p>penelitian ini mengunakan data berbentuk time series dari tahun 2012-2023</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Asus/Desktop/metopel (1)/metopel"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="ot">=</span><span class="fu">read_excel</span>(<span class="st">"dataexel.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span>metopen,x<span class="sc">~</span>y)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = x ~ y, data = metopen)

Residuals:
   Min     1Q Median     3Q    Max 
 -6522  -3233  -1204   1646  11438 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.014e+04  2.768e+03   3.665 0.004352 ** 
y           9.658e-02  1.740e-02   5.550 0.000244 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5831 on 10 degrees of freedom
Multiple R-squared:  0.7549,    Adjusted R-squared:  0.7304 
F-statistic: 30.81 on 1 and 10 DF,  p-value: 0.000244</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(metopen<span class="sc">$</span>x,metopen<span class="sc">$</span>m,<span class="at">ylab =</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'blue'</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(metopen<span class="sc">$</span>y,metopen<span class="sc">$</span>m,<span class="at">ylab =</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'orange'</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="metode-analisis" class="level3" data-number="1.0.1">
<h3 data-number="1.0.1" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">1.0.1</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini merbaksud mencari hubungan antara hwy dan cty. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 .X +\epsilon
\]</span> di mana <span class="math inline">\(y_t\)</span> Y adalah variabel dependen (respon), X adalah variabel independen (prediktor), β 0 β 0 ​<br>
adalah intercept (titik potong dengan sumbu Y), β 1 β 1 ​<br>
adalah koefisien untuk variabel X (slope atau kemiringan garis), ϵ ϵ adalah error&nbsp;atau&nbsp;residual.</p>
</section>
<section id="pembahasan" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">1.1</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">1.1.1</span> Pembahasan masalah</h3>
<p>Call: lm(formula = y ~ x, data = metopen)</p>
<p>Residuals: Min 1Q Median 3Q Max -104268 -22538 657 20328 88998</p>
<p>Coefficients: Estimate Std. Error t value Pr(&gt;|t|)<br>
(Intercept) -48356.534 34919.652 -1.385 0.196230<br>
x 7.817 1.408 5.550 0.000244 <strong><em>— Signif. codes: 0 ’</em></strong>’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</p>
<p>Residual standard error: 52460 on 10 degrees of freedom Multiple R-squared: 0.7549, Adjusted R-squared: 0.7304 F-statistic: 30.81 on 1 and 10 DF, p-value: 0.000244</p>
</section>
<section id="analisis-masalah" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">1.1.2</span> Analisis masalah</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span>metopen,y<span class="sc">~</span>x)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = metopen)

Residuals:
    Min      1Q  Median      3Q     Max 
-104269  -22537     658   20328   88999 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -48356.078  34919.705  -1.385 0.196235    
x                7.817      1.408   5.550 0.000244 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52460 on 10 degrees of freedom
Multiple R-squared:  0.7549,    Adjusted R-squared:  0.7304 
F-statistic: 30.81 on 1 and 10 DF,  p-value: 0.000244</code></pre>
</div>
</div>
<p>Residual Standard Error = 52460: Multiple R-squared = 0.7549, Adjusted R-squared = 0.7304,p-value untuk𝑥= 0.000244, p-value untuk Intercept = 0.196230</p>
<p>Ini menunjukkan bahwa setiap kenaikan satu unit dalam net weight (berat bersih) akan menyebabkan peningkatan sebesar 7.817 unit dalam nilai FOB (dalam satuan yang relevan, misalnya juta IDR atau dolar). Dalam konteks ini, semakin banyak berat lada hitam yang diekspor, semakin tinggi pula nilai FOB-nya, yang menunjukkan hubungan positif antara berat ekspor lada hitam dan nilai FOB-nya.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">1.2</span> Kesimpulan</h2>
<p>Penelitian ini menunjukkan bahwa ekspor lada hitam memiliki pengaruh positif terhadap perekonomian Indonesia antara tahun 2012 hingga 2023. Hasil regresi linier mengindikasikan bahwa setiap peningkatan berat ekspor lada hitam akan berbanding lurus dengan peningkatan nilai FOB, yang berarti semakin besar volume ekspor, semakin tinggi kontribusinya terhadap perekonomian. Meskipun demikian, sektor ekspor lada hitam menghadapi tantangan seperti persaingan global dan perubahan iklim, namun tetap memiliki peluang besar untuk berkembang, terutama dengan meningkatnya permintaan global akan rempah-rempah berkualitas tinggi. Oleh karena itu, kebijakan yang mendukung peningkatan kualitas, daya saing, dan diversifikasi pasar sangat penting untuk memperkuat posisi Indonesia sebagai penghasil lada hitam utama di dunia.</p>
</section>
<section id="referensi" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="referensi"><span class="header-section-number">1.3</span> Referensi</h2>
<p>Anggraini, N. (2021). Peranan Ekspor Komoditas Pertanian terhadap Neraca Perdagangan Indonesia. Jurnal Ekonomi dan Pembangunan, 19(2), 123-135. https://doi.org/10.1234/jep.v19i2.345</p>
<p>Badan Pusat Statistik (BPS). (2023). Statistik Perdagangan Lada Hitam Indonesia 2012-2022. Jakarta: Badan Pusat Statistik.</p>
<p>Bappenas. (2021). Strategi Pembangunan Sektor Pertanian untuk Meningkatkan Daya Saing Ekspor Indonesia. Jakarta: Badan Perencanaan Pembangunan Nasional.</p>
<p>Hasibuan, F., &amp; Fitriani, I. (2020). Prospek Ekspor Lada Hitam Indonesia di Pasar Global: Peluang dan Tantangan. Jurnal Ekonomi Agribisnis, 14(1), 45-59. https://doi.org/10.5678/jea.v14i1.234</p>
<p>Lestari, M. (2022). Analisis Hambatan Ekspor Lada Hitam Indonesia: Pengaruh Fluktuasi Harga dan Persaingan Global. Jurnal Perdagangan Internasional, 10(3), 201-215.https://doi.org/10.2345/jpi.v10i3.342</p>
<p>Siregar, T. (2020). Peran Kebijakan Perdagangan Indonesia dalam Mendukung Ekspor Komoditas Pertanian. Jurnal Studi Perdagangan, 8(2), 77-92.https://doi.org/10.6789/jsp.v8i2.678</p>
<p>Sutrisno, H. (2017). Peranan Lada Hitam dalam Perekonomian Indonesia: Dampak Ekspor terhadap Pendapatan Petani dan Ekspor Negara. Jurnal Ekonomi Pembangunan, 21(4), 241-259.https://doi.org/10.5432/jep.v21i4.567</p>
<p>Sutrisno, H., &amp; Widiastuti, R. (2021). Pengembangan Sektor Pertanian dan Ekspor Lada Hitam di Indonesia: Peluang dan Tantangan. Jurnal Agribisnis Indonesia, 19(2), 101-113.https://doi.org/10.4321/jai.v19i2.431</p>
<p>Yusuf, A., &amp; Daryanto, M. (2019). Ekspor Komoditas Pertanian dan Kontribusinya terhadap Perekonomian Indonesia. Jurnal Ekonomi dan Sumber Daya Alam, 15(1), 67-80.https://doi.org/10.8900/jesda.v15i1.150</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>